[package]
name = "greenhouse-exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.2"
serde = "1.0.145"
serde_json = "1.0.85"
